
DROP TABLE PAYMENT CASCADE CONSTRAINTS;
DROP TABLE BILL CASCADE CONSTRAINTS;
DROP TABLE TREATMENT CASCADE CONSTRAINTS;
DROP TABLE APPOINTMENT CASCADE CONSTRAINTS;
DROP TABLE PATIENT CASCADE CONSTRAINTS;
DROP TABLE DOCTOR CASCADE CONSTRAINTS;
DROP TABLE DEPARTMENT CASCADE CONSTRAINTS;

CREATE TABLE DEPARTMENT (
    Dept_ID INT PRIMARY KEY,
    Dept_Name VARCHAR2(100) NOT NULL UNIQUE
);

CREATE TABLE DOCTOR (
    Doctor_ID INT PRIMARY KEY,
    Name VARCHAR2(100) NOT NULL,
    Specialization VARCHAR2(100),
    Dept_ID INT,
    CONSTRAINT fk_doctor_dept FOREIGN KEY (Dept_ID) REFERENCES DEPARTMENT(Dept_ID)
);

CREATE TABLE PATIENT (
    Patient_ID INT PRIMARY KEY,
    Name VARCHAR2(100) NOT NULL,
    DOB DATE,
    Gender VARCHAR2(10) CHECK (Gender IN ('Male', 'Female', 'Other')),
    Phone VARCHAR2(15) UNIQUE,
    Address VARCHAR2(255)
);

CREATE TABLE APPOINTMENT (
    App_ID INT PRIMARY KEY,
    Patient_ID INT,
    Doctor_ID INT,
    App_Date TIMESTAMP NOT NULL,
    Status VARCHAR2(20) DEFAULT 'Scheduled' CHECK (Status IN ('Scheduled', 'Completed', 'Cancelled')),
    CONSTRAINT fk_app_patient FOREIGN KEY (Patient_ID) REFERENCES PATIENT(Patient_ID),
    CONSTRAINT fk_app_doctor FOREIGN KEY (Doctor_ID) REFERENCES DOCTOR(Doctor_ID)
);

CREATE TABLE TREATMENT (
    Treatment_ID INT PRIMARY KEY,
    App_ID INT UNIQUE, -- 1 to 1 relationship with Appointment
    Diagnosis VARCHAR2(255) NOT NULL,
    Treatment_Desc VARCHAR2(500),
    Cost DECIMAL(10, 2) CHECK (Cost >= 0),
    CONSTRAINT fk_treat_app FOREIGN KEY (App_ID) REFERENCES APPOINTMENT(App_ID)
);

CREATE TABLE BILL (
    Bill_ID INT PRIMARY KEY,
    Treatment_ID INT UNIQUE, -- 1 to 1 relationship with Treatment
    Total_Amount DECIMAL(10, 2),
    Bill_Date DATE DEFAULT SYSDATE,
    Status VARCHAR2(20) DEFAULT 'Unpaid' CHECK (Status IN ('Unpaid', 'Partial', 'Paid')),
    CONSTRAINT fk_bill_treat FOREIGN KEY (Treatment_ID) REFERENCES TREATMENT(Treatment_ID)
);

CREATE TABLE PAYMENT (
    Payment_ID INT PRIMARY KEY,
    Bill_ID INT,
    Amount_Paid DECIMAL(10, 2) CHECK (Amount_Paid > 0),
    Payment_Date DATE DEFAULT SYSDATE,
    Mode_Of_Payment VARCHAR2(50),
    CONSTRAINT fk_pay_bill FOREIGN KEY (Bill_ID) REFERENCES BILL(Bill_ID)
);